[2022-12-03T00:18:42.463+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_s3_dag.download_dataset_task scheduled__2022-12-02T00:00:00+00:00 [queued]>
[2022-12-03T00:18:42.513+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_s3_dag.download_dataset_task scheduled__2022-12-02T00:00:00+00:00 [queued]>
[2022-12-03T00:18:42.514+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-03T00:18:42.518+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-12-03T00:18:42.520+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-03T00:18:42.556+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-12-02 00:00:00+00:00
[2022-12-03T00:18:42.605+0000] {standard_task_runner.py:55} INFO - Started process 9125 to run task
[2022-12-03T00:18:42.656+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_s3_dag', 'download_dataset_task', 'scheduled__2022-12-02T00:00:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_s3_dag.py', '--cfg-path', '/tmp/tmpdrgqzq9s']
[2022-12-03T00:18:42.668+0000] {standard_task_runner.py:83} INFO - Job 139: Subtask download_dataset_task
[2022-12-03T00:18:42.979+0000] {task_command.py:376} INFO - Running <TaskInstance: data_ingestion_s3_dag.download_dataset_task scheduled__2022-12-02T00:00:00+00:00 [running]> on host 7d1b5368210b
[2022-12-03T00:18:43.369+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_s3_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T00:00:00+00:00
[2022-12-03T00:18:43.455+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-03T00:18:43.464+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv > /opt/***/yellow_tripdata_2021-01.csv']
[2022-12-03T00:18:43.507+0000] {subprocess.py:86} INFO - Output:
[2022-12-03T00:18:43.638+0000] {subprocess.py:93} INFO - curl: (6) Could not resolve host: s3.amazonaws.com
[2022-12-03T00:18:43.645+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2022-12-03T00:18:43.688+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-12-03T00:18:43.716+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_s3_dag, task_id=download_dataset_task, execution_date=20221202T000000, start_date=20221203T001842, end_date=20221203T001843
[2022-12-03T00:18:43.762+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 139 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 6.; 9125)
[2022-12-03T00:18:43.799+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-03T00:18:43.851+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
