[2022-12-03T00:24:12.518+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_s3_dag.download_dataset_task scheduled__2022-12-02T00:00:00+00:00 [queued]>
[2022-12-03T00:24:12.536+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_s3_dag.download_dataset_task scheduled__2022-12-02T00:00:00+00:00 [queued]>
[2022-12-03T00:24:12.538+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-03T00:24:12.541+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-12-03T00:24:12.543+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-03T00:24:12.575+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-12-02 00:00:00+00:00
[2022-12-03T00:24:12.585+0000] {standard_task_runner.py:55} INFO - Started process 9151 to run task
[2022-12-03T00:24:12.595+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_s3_dag', 'download_dataset_task', 'scheduled__2022-12-02T00:00:00+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_s3_dag.py', '--cfg-path', '/tmp/tmp58pci8x7']
[2022-12-03T00:24:12.601+0000] {standard_task_runner.py:83} INFO - Job 140: Subtask download_dataset_task
[2022-12-03T00:24:12.753+0000] {task_command.py:376} INFO - Running <TaskInstance: data_ingestion_s3_dag.download_dataset_task scheduled__2022-12-02T00:00:00+00:00 [running]> on host 7d1b5368210b
[2022-12-03T00:24:12.846+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_s3_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T00:00:00+00:00
[2022-12-03T00:24:12.855+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-03T00:24:12.859+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv > /opt/***/yellow_tripdata_2021-01.csv']
[2022-12-03T00:24:12.888+0000] {subprocess.py:86} INFO - Output:
[2022-12-03T00:24:12.915+0000] {subprocess.py:93} INFO - curl: (6) Could not resolve host: s3.amazonaws.com
[2022-12-03T00:24:12.919+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2022-12-03T00:24:12.938+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-12-03T00:24:12.946+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=data_ingestion_s3_dag, task_id=download_dataset_task, execution_date=20221202T000000, start_date=20221203T002412, end_date=20221203T002412
[2022-12-03T00:24:12.975+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 140 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 6.; 9151)
[2022-12-03T00:24:13.016+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-03T00:24:13.040+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
