[2022-11-26T10:12:00.745+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_s3_dag.upload_to_s3 manual__2022-11-26T10:11:55.781491+00:00 [queued]>
[2022-11-26T10:12:00.751+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_s3_dag.upload_to_s3 manual__2022-11-26T10:11:55.781491+00:00 [queued]>
[2022-11-26T10:12:00.752+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T10:12:00.753+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-11-26T10:12:00.754+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T10:12:00.761+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2022-11-26 10:11:55.781491+00:00
[2022-11-26T10:12:00.766+0000] {standard_task_runner.py:55} INFO - Started process 2741 to run task
[2022-11-26T10:12:00.769+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_s3_dag', 'upload_to_s3', 'manual__2022-11-26T10:11:55.781491+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_s3_dag.py', '--cfg-path', '/tmp/tmph6usraf8']
[2022-11-26T10:12:00.771+0000] {standard_task_runner.py:83} INFO - Job 117: Subtask upload_to_s3
[2022-11-26T10:12:00.810+0000] {task_command.py:376} INFO - Running <TaskInstance: data_ingestion_s3_dag.upload_to_s3 manual__2022-11-26T10:11:55.781491+00:00 [running]> on host 7d1b5368210b
[2022-11-26T10:12:00.852+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_s3_dag
AIRFLOW_CTX_TASK_ID=upload_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-11-26T10:11:55.781491+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-26T10:11:55.781491+00:00
[2022-11-26T10:12:00.862+0000] {base_aws.py:120} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2022-11-26T10:12:00.875+0000] {credentials.py:1180} INFO - Found credentials in environment variables.
[2022-11-26T10:12:05.311+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-11-26T10:12:05.320+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=data_ingestion_s3_dag, task_id=upload_to_s3, execution_date=20221126T101155, start_date=20221126T101200, end_date=20221126T101205
[2022-11-26T10:12:05.378+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-26T10:12:05.390+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
