[2022-12-02T00:05:03.285+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_s3_dag.download_dataset_task scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2022-12-02T00:05:03.295+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_s3_dag.download_dataset_task scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2022-12-02T00:05:03.297+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T00:05:03.298+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-12-02T00:05:03.300+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-02T00:05:03.311+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-12-01 00:00:00+00:00
[2022-12-02T00:05:03.319+0000] {standard_task_runner.py:55} INFO - Started process 42029 to run task
[2022-12-02T00:05:03.325+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_s3_dag', 'download_dataset_task', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_s3_dag.py', '--cfg-path', '/tmp/tmptkmuntd1']
[2022-12-02T00:05:03.329+0000] {standard_task_runner.py:83} INFO - Job 138: Subtask download_dataset_task
[2022-12-02T00:05:03.381+0000] {task_command.py:376} INFO - Running <TaskInstance: data_ingestion_s3_dag.download_dataset_task scheduled__2022-12-01T00:00:00+00:00 [running]> on host 7d1b5368210b
[2022-12-02T00:05:03.426+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_s3_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-01T00:00:00+00:00
[2022-12-02T00:05:03.429+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-02T00:05:03.430+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv > /opt/***/yellow_tripdata_2021-01.csv']
[2022-12-02T00:05:03.446+0000] {subprocess.py:86} INFO - Output:
[2022-12-02T00:05:03.470+0000] {subprocess.py:93} INFO - curl: (6) Could not resolve host: s3.amazonaws.com
[2022-12-02T00:05:03.472+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2022-12-02T00:05:03.484+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-12-02T00:05:03.488+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=data_ingestion_s3_dag, task_id=download_dataset_task, execution_date=20221201T000000, start_date=20221202T000503, end_date=20221202T000503
[2022-12-02T00:05:03.500+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 138 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 6.; 42029)
[2022-12-02T00:05:03.539+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-02T00:05:03.560+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
